#!/usr/bin/env python3
"""CURRICULUM -- does easy-to-hard sampling unlock the hierarchy?

    python3 curriculum.py --steps 48000 --seed 1 --save K1.pt          # curriculum
    python3 curriculum.py --steps 48000 --seed 1 --simple-frac 0 --save K0.pt
    python3 curriculum.py --load K1.pt                                 # probes only

THE IMPORT
----------
Qiu et al. (arXiv:2407.15360) on transformer multiplication: baseline 0.0%,
+depth 1.6%, +depth+reverse 8.7%, +depth+reverse+SAMPLE 99.9%. Raising the
proportion of simple examples mattered more than everything else combined.
Their sharpest line: training directly on the hard case prevented the model
from learning even the basic rules, so a model trained on m x m then failed at
m x u, which it could otherwise do.

This corpus has no curriculum. Every sequence is a complete depth-L tree --
the analogue of training only on ddddd x ddddd. And the symptom matches: the
model sits at local 2.04 against a 1.60 floor, so it has not mastered the EASY
component either, while `higher` never moves off 3.77.

WHAT A SIMPLE EXAMPLE IS HERE
-----------------------------
A shallower tree. A depth-k sample is generated by starting at level k rather
than level L, giving 2^k leaves, then LEFT-PADDING to SEQ with a pad token and
masking the padded targets. Same rule tables, same vocabulary, same positional
alignment for the real leaves -- only the number of composition levels varies.

    depth 1: 2 leaves    one production, the sibling rule alone
    depth 2: 4 leaves    two levels
    depth 3: 8 leaves
    depth 4: 16 leaves   the full task, and the ONLY thing evaluated

Evaluation is always on full depth-L trees, so the numbers stay comparable to
every other arm. --simple-frac 0 is the matched control: identical code path,
no shallow samples.
"""
import json, math, argparse, time, random
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F

ap = argparse.ArgumentParser()
ap.add_argument("--data", default="/tmp")
ap.add_argument("--d-model", type=int, default=64)
ap.add_argument("--n-heads", type=int, default=4)
ap.add_argument("--layers", type=int, default=4)
ap.add_argument("--steps", type=int, default=48000)
ap.add_argument("--batch", type=int, default=32)
ap.add_argument("--lr", type=float, default=1e-3)
ap.add_argument("--simple-frac", type=float, default=0.5,
                help="fraction of each batch drawn from shallower trees")
ap.add_argument("--anneal", action="store_true",
                help="decay simple-frac linearly to 0 over training")
ap.add_argument("--seed", type=int, default=1)
ap.add_argument("--save", default=""); ap.add_argument("--load", default="")
ap.add_argument("--eval-every", type=int, default=2000)
ap.add_argument("--n-probe", type=int, default=4000)
a = ap.parse_args()

M = json.load(open(f"{a.data}/rhm_meta.json"))
L, V, SEQ, NLEAF = M["depth"], M["nsym"], M["seq_len"], M["nleaf"]
KIND = M["pos_kind"]
R = {int(l): {int(i): [tuple(t) for t in v] for i, v in d.items()}
     for l, d in M["rules_all"].items()}
PAD = NLEAF                      # extra id for left padding
VOCAB = NLEAF + 1
IGN = -100
rng = random.Random(a.seed); torch.manual_seed(a.seed)

def sample(nb, depth=None):
    """depth=None -> full L. Shallower trees are LEFT-padded to SEQ so the
    real leaves keep their positional alignment with the full task."""
    X = torch.full((nb, SEQ), PAD, dtype=torch.long)
    Yt = torch.full((nb, SEQ), IGN, dtype=torch.long)
    Y = {l: torch.zeros(nb, SEQ, dtype=torch.long) for l in range(1, L+1)}
    for b in range(nb):
        d = depth if depth is not None else L
        n = 2 ** d
        off0 = SEQ - n                                  # left pad
        def go(s, l, off):
            if l > 0 and off >= 0:
                for t in range(off, min(off + 2**l, SEQ)):
                    if l <= L: Y[l][b, t] = s
            if l == 0: return [s]
            x, y = rng.choice(R[l][s])
            return go(x, l-1, off) + go(y, l-1, off + 2**(l-1))
        leaves = go(rng.randrange(V), d, off0)
        X[b, off0:] = torch.tensor(leaves)
    # next-token targets; padded positions and the last slot are ignored
    Yt[:, :-1] = X[:, 1:]
    Yt[X[:, :] == PAD] = IGN
    Yt[:, -1] = IGN
    pad_next = (X[:, 1:] == PAD)
    Yt[:, :-1][pad_next] = IGN
    return X, Yt, Y

class Attn(nn.Module):
    def __init__(s, d, nh):
        super().__init__(); s.nh, s.dh = nh, d//nh
        s.q, s.k, s.v, s.o = (nn.Linear(d, d, bias=False) for _ in range(4))
    def forward(s, x):
        B, T, D = x.shape
        sp = lambda t: t.view(B, T, s.nh, s.dh).transpose(1, 2)
        q, k, v = sp(s.q(x)), sp(s.k(x)), sp(s.v(x))
        att = (q @ k.transpose(-2, -1)) / math.sqrt(s.dh)
        m = torch.triu(torch.ones(T, T, dtype=torch.bool, device=x.device), 1)
        return s.o(((att.masked_fill(m, float("-inf")).softmax(-1)) @ v)
                   .transpose(1, 2).contiguous().view(B, T, D))

class Block(nn.Module):
    def __init__(s, d, nh):
        super().__init__()
        s.n1, s.at, s.n2 = nn.LayerNorm(d), Attn(d, nh), nn.LayerNorm(d)
        s.mlp = nn.Sequential(nn.Linear(d, 4*d), nn.GELU(), nn.Linear(4*d, d))
    def forward(s, x):
        x = x + s.at(s.n1(x)); return x + s.mlp(s.n2(x))

class LM(nn.Module):
    def __init__(s, d, nh, nl):
        super().__init__()
        s.te = nn.Embedding(VOCAB, d); s.pe = nn.Embedding(SEQ+4, d)
        s.blocks = nn.ModuleList([Block(d, nh) for _ in range(nl)])
        s.lnf = nn.LayerNorm(d); s.head = nn.Linear(d, VOCAB)
    def hidden(s, idx):
        h = s.te(idx) + s.pe(torch.arange(idx.shape[1], device=idx.device))[None]
        for b in s.blocks: h = b(h)
        return s.lnf(h)
    def forward(s, idx, tgt=None):
        h = s.hidden(idx); lg = s.head(h)
        loss = None
        if tgt is not None:
            loss = F.cross_entropy(lg.reshape(-1, VOCAB), tgt.reshape(-1),
                                   ignore_index=IGN)
        return lg, h, loss

model = LM(a.d_model, a.n_heads, a.layers)
print(f"  {a.layers}-layer d={a.d_model}  simple-frac={a.simple_frac}"
      f"{' (annealed)' if a.anneal else ''}  "
      f"params={sum(p.numel() for p in model.parameters()):,}  seed={a.seed}")
print(f"  floors: local 1.6034  higher 3.5527   "
      f"transformer 48k: local 2.04  higher 3.77")

def eval_full(m, nb=256):
    with torch.no_grad():
        X, Yt, _ = sample(nb)                       # always full depth
        lg, _, _ = m(X)
        ce = F.cross_entropy(lg.reshape(-1, VOCAB), Yt.reshape(-1),
                             ignore_index=IGN, reduction='none').view(X.shape)
        k = (Yt != IGN).double()
        lo = float((ce*k)[:, [t for t in range(SEQ-1) if KIND[t+1]=="local"]].sum()
                   / k[:, [t for t in range(SEQ-1) if KIND[t+1]=="local"]].sum())
        hi = float((ce*k)[:, [t for t in range(SEQ-1) if KIND[t+1]=="higher"]].sum()
                   / k[:, [t for t in range(SEQ-1) if KIND[t+1]=="higher"]].sum())
    return lo, hi

if a.load:
    model.load_state_dict(torch.load(a.load, map_location="cpu")); model.eval()
else:
    opt = torch.optim.AdamW(model.parameters(), lr=a.lr, betas=(0.9, 0.95),
                            weight_decay=0.01)
    t0 = time.time()
    for step in range(1, a.steps+1):
        frac = a.simple_frac * (1 - step/a.steps) if a.anneal else a.simple_frac
        ns = int(round(a.batch * frac))
        Xs, Ys = [], []
        if ns > 0:
            per = max(1, ns // max(1, L-1))
            for d in range(1, L):                  # depths 1..L-1
                X1, Y1, _ = sample(per, depth=d); Xs.append(X1); Ys.append(Y1)
        X2, Y2, _ = sample(a.batch - sum(x.shape[0] for x in Xs))
        Xs.append(X2); Ys.append(Y2)
        X, Yt = torch.cat(Xs), torch.cat(Ys)
        _, _, loss = model(X, Yt)
        opt.zero_grad(); loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0); opt.step()
        if step % a.eval_every == 0 or step == 1:
            lo, hi = eval_full(model)
            print(f"  {step:6d}  local={lo:.4f}  higher={hi:.4f}"
                  f"  [frac={frac:.2f}]  [{time.time()-t0:.0f}s]")
    if a.save: torch.save(model.state_dict(), a.save); print(f"  saved {a.save}")

def probe(Hm, lab, nc, ep=300):
    n = Hm.shape[0]; k = int(0.7*n); i = torch.randperm(n)
    tr, te = i[:k], i[k:]
    w = nn.Linear(Hm.shape[1], nc)
    o = torch.optim.Adam(w.parameters(), lr=3e-3, weight_decay=1e-4)
    for _ in range(ep):
        o.zero_grad(); F.cross_entropy(w(Hm[tr]), lab[tr]).backward(); o.step()
    with torch.no_grad():
        return float((w(Hm[te]).argmax(-1) == lab[te]).float().mean())

model.eval()
with torch.no_grad():
    X, _, Y = sample(a.n_probe); h = model.hidden(X)
print(f"\n  DECODING THE LATENT PARSE   (chance = {1.0/V:.4f})")
tf = {(1,'local'):0.479,(1,'higher'):0.213,(2,'local'):0.072,(2,'higher'):0.064,
      (3,'local'):0.028,(3,'higher'):0.024,(4,'local'):0.020,(4,'higher'):0.018}
print(f"  {'level':>7}{'kind':>9}{'acc':>9}{'shuf':>8}   transformer")
for l in range(1, L+1):
    for kind in ("local", "higher"):
        ts = [t for t in range(SEQ) if KIND[t] == kind]
        f = torch.cat([h[:, t, :] for t in ts])
        lab = torch.tensor([int(Y[l][i, t]) for t in ts for i in range(h.shape[0])],
                           dtype=torch.long)
        print(f"  {l:>7}{kind:>9}{probe(f, lab, V):>9.3f}"
              f"{probe(f, lab[torch.randperm(len(lab))], V):>8.3f}"
              f"   {tf[(l,kind)]:.3f}")
print(f"\n  level 3 off 0.028 => curriculum was the missing ingredient")
print(f"  `local` below 2.04 => the easy component was being starved by")
print(f"  training only on the hardest case, exactly as Qiu et al. report")
