#!/usr/bin/env python3
"""PARSE_MERGE -- two structures over the same tokens whose heads cannot match.

    python3 parse_merge.py --mix 0.3
    python3 parse_merge.py --mix 0.5 --sweep-evidence

THE SITUATION
-------------
Two accounts of the same data, with different constituent structure -- not two
values of one latent, which is ordinary Bayesian updating, but two BRACKETINGS
that cross, so no relabelling of symbols can turn one into the other.

    A (rows)     {0,1,2} {3,4,5} {6,7,8}
    B (columns)  {0,3,6} {1,4,7} {2,5,8}

Every A-constituent meets every B-constituent in exactly one leaf. The heads
cannot be matched: there is no permutation of A's symbols carrying A's
constituents to B's, because the covers overlap without refining. This is the
formal version of "two readings of the same sentence" or "two decompositions of
the same mechanism" -- structures that compete rather than differ in a
parameter.

WHAT IS MEASURED
----------------
  1. The deficit. Fit a single tree under A, a single tree under B, and a
     MIXTURE that lets each sequence choose. Held-out log-likelihood of each,
     against the generating model. The gap between the best single tree and
     the mixture is the cost, in nats, of insisting on one structure.

  2. The parse posterior. For each held-out sequence, P(A | tokens). Scored
     against the bracketing that actually generated it, so the number is
     checkable rather than assumed.

  3. Evidence accumulation. Reveal the leaves one constituent at a time and
     track the posterior. This is the honest form of "more data tilts the
     balance": the tilt is measured against ground truth, and the calibration
     is reported, so over-confidence is visible.

WHY THIS AND NOT A SINGLE HIERARCHY
-----------------------------------
If two accounts share a structure and differ only in where mass sits at one
node, the mixture IS a single tree and the merge is just an E-step: the data
always glue (the single-source theorem), and nothing structural is at stake.
Only crossing bracketings make the merge non-trivial, and then the right object
is a mixture over parses, not one tree with adjusted probabilities.
"""
import argparse, itertools
import numpy as np

ap = argparse.ArgumentParser()
ap.add_argument("--mix", type=float, default=0.3, help="P(generated by B)")
ap.add_argument("--n", type=int, default=40000)
ap.add_argument("--n-val", type=int, default=5000)
ap.add_argument("--nsym", type=int, default=6)
ap.add_argument("--nleaf", type=int, default=9)
ap.add_argument("--nrules", type=int, default=3)
ap.add_argument("--sweeps", type=int, default=40)
ap.add_argument("--sweep-evidence", action="store_true")
ap.add_argument("--seed", type=int, default=0)
a = ap.parse_args()
V, A, m = a.nsym, a.nleaf, a.nrules
ROWS = [(0, 1, 2), (3, 4, 5), (6, 7, 8)]
COLS = [(0, 3, 6), (1, 4, 7), (2, 5, 8)]
rng = np.random.RandomState(a.seed)

# ------------------------------------------------------------- generator
top = {s: [tuple(rng.randint(0, V, 3)) for _ in range(m)] for s in range(V)}
bot = {s: [tuple(rng.randint(0, A, 3)) for _ in range(m)] for s in range(V)}

def generate(n, mix):
    X = np.zeros((n, 9), dtype=np.int64); lab = (rng.rand(n) < mix).astype(int)
    for i in range(n):
        groups = COLS if lab[i] else ROWS
        r = rng.randint(V); kids = top[r][rng.randint(m)]
        for g, sym in zip(groups, kids):
            leaves = bot[sym][rng.randint(m)]
            for pos, lf in zip(g, leaves): X[i, pos] = lf
    return X, lab

XT, LT = generate(a.n, a.mix)
XV, LV = generate(a.n_val, a.mix)
print(f"  parse_merge: 9 leaves, V={V}, leaf alphabet={A}, {m} rules/symbol")
print(f"  P(B) = {a.mix},  {a.n} train / {a.n_val} held-out")
print(f"  A {ROWS}\n  B {COLS}   -- every A-constituent meets every B-constituent")
print(f"  in one leaf, so no relabelling carries one to the other.\n")

# --------------------------------------------------- one tree under a bracketing
def em_tree(X, groups, sweeps, E=None, T=None, pri=None, mask=None):
    """root -> three constituent symbols -> three leaves each. mask, if given,
    is a boolean per leaf: False means that leaf is unobserved."""
    n = len(X); rs = np.random.RandomState(1)
    if E is None:
        E = rs.rand(V, A, A, A)+1.0; E /= E.sum((1, 2, 3), keepdims=True)
        T = rs.rand(V, V, V, V)+1.0; T /= T.sum((1, 2, 3), keepdims=True)
        pri = np.full(V, 1.0/V)
    idx = [np.array(g) for g in groups]
    for _ in range(sweeps):
        beta = np.stack([emit_beta(E, X, g, mask) for g in idx], 1)   # n x 3 x V
        joint = np.einsum('r,rabc,na,nb,nc->nrabc', pri, T,
                          beta[:, 0], beta[:, 1], beta[:, 2])
        Z = joint.reshape(n, -1).sum(1)
        w = joint/np.maximum(Z[:, None, None, None, None], 1e-300)
        Tn = w.sum(0)+1e-9; T = Tn/Tn.sum((1, 2, 3), keepdims=True)
        pri = w.reshape(n, V, -1).sum(2).sum(0); pri /= pri.sum()
        q = [w.sum((1, 3, 4)), w.sum((1, 2, 4)), w.sum((1, 2, 3))]
        En = np.zeros_like(E)
        for k, g in enumerate(idx):
            np.add.at(En, (slice(None), X[:, g[0]], X[:, g[1]], X[:, g[2]]), q[k].T)
        En += 1e-9; E = En/En.sum((1, 2, 3), keepdims=True)
    return E, T, pri

def emit_beta(E, X, g, mask=None):
    """P(the three leaves of this constituent | its symbol), with unobserved
    leaves summed out"""
    if mask is None or all(mask[p] for p in g):
        return E[:, X[:, g[0]], X[:, g[1]], X[:, g[2]]].T
    ax = tuple(1+k for k, p in enumerate(g) if not mask[p])
    Em = E.sum(axis=ax)
    obs = [p for p in g if mask[p]]
    if not obs: return np.ones((len(X), V))
    if len(obs) == 1: return Em[:, X[:, obs[0]]].T
    return Em[:, X[:, obs[0]], X[:, obs[1]]].T

def seq_loglik(X, groups, E, T, pri, mask=None):
    idx = [np.array(g) for g in groups]
    beta = np.stack([emit_beta(E, X, g, mask) for g in idx], 1)
    joint = np.einsum('r,rabc,na,nb,nc->n', pri, T, beta[:, 0], beta[:, 1], beta[:, 2])
    return np.log(np.maximum(joint, 1e-300))

EA = em_tree(XT, ROWS, a.sweeps)
EB = em_tree(XT, COLS, a.sweeps)
llA = seq_loglik(XV, ROWS, *EA).mean()
llB = seq_loglik(XV, COLS, *EB).mean()

# ------------------------------------------------------- mixture over parses
wA = 0.5
for _ in range(25):
    la = seq_loglik(XT, ROWS, *EA); lb = seq_loglik(XT, COLS, *EB)
    pa = 1.0/(1.0 + np.exp(np.clip(lb-la, -700, 700))*(1-wA)/max(wA, 1e-12))
    wA = float(pa.mean())
la = seq_loglik(XV, ROWS, *EA); lb = seq_loglik(XV, COLS, *EB)
mx = np.logaddexp(np.log(max(wA, 1e-12))+la, np.log(max(1-wA, 1e-12))+lb)
llM = mx.mean()

print(f"  HELD-OUT LOG-LIKELIHOOD PER SEQUENCE")
print(f"    single tree, bracketing A    {llA:>10.4f}")
print(f"    single tree, bracketing B    {llB:>10.4f}")
print(f"    mixture over both parses     {llM:>10.4f}   (weight on A "
      f"{wA:.3f}, true {1-a.mix:.3f})")
print(f"    deficit of the best single tree: {llM-max(llA, llB):.4f} nats/seq")
print(f"    -- the cost of insisting on one structure. It is zero only when one")
print(f"       bracketing generated everything.\n")

# ----------------------------------------------------- parse posterior, scored
post = 1.0/(1.0 + np.exp(np.clip(lb-la, -700, 700))*(1-wA)/max(wA, 1e-12))
pred = (post < 0.5).astype(int)
acc = float((pred == LV).mean())
print(f"  PARSE POSTERIOR, scored against the bracketing that actually generated")
print(f"  each held-out sequence")
print(f"    accuracy {acc:.4f}   (base rate {max(a.mix, 1-a.mix):.4f})")
print(f"    {'P(A) bin':>12}{'count':>8}{'actually A':>12}   calibration")
for lo, hi in ((0.0, .2), (.2, .4), (.4, .6), (.6, .8), (.8, 1.0)):
    sel = (post >= lo) & (post < hi if hi < 1.0 else post <= 1.0)
    if sel.sum() == 0: continue
    frac = float((LV[sel] == 0).mean())
    print(f"    {f'{lo:.1f}-{hi:.1f}':>12}{int(sel.sum()):>8}{frac:>12.3f}"
          f"   {'well calibrated' if abs(frac-(lo+hi)/2) < 0.15 else 'OFF'}")

# --------------------------------------------------- evidence accumulation
if a.sweep_evidence:
    print(f"\n  EVIDENCE ACCUMULATION: leaves revealed one A-constituent at a time")
    print(f"    {'leaves seen':>12}{'mean P(correct parse)':>24}{'accuracy':>10}")
    for k in range(1, 4):
        mask = [False]*9
        for g in ROWS[:k]:
            for p in g: mask[p] = True
        lak = seq_loglik(XV, ROWS, *EA, mask=mask)
        lbk = seq_loglik(XV, COLS, *EB, mask=mask)
        pk = 1.0/(1.0+np.exp(np.clip(lbk-lak, -700, 700))*(1-wA)/max(wA, 1e-12))
        conf = np.where(LV == 0, pk, 1-pk)
        print(f"    {3*k:>12}{float(conf.mean()):>24.4f}"
              f"{float(((pk < 0.5).astype(int) == LV).mean()):>10.4f}")
    print(f"    Confidence rises with evidence, and it is scored against the")
    print(f"    truth at every step, so a tilt that is not earned shows up as")
    print(f"    accuracy that fails to follow.")
