"""Recursive training on Corpus B (model collapse), warm-started EM.

gen 0      split-merge fit on real data (cH/fit.npz)
gen g>0    sample N sequences from model g-1, refit by EM warm-started at model g-1
arms       replace     : train on the newest synthetic sample only
           accumulate  : train on real data + every synthetic sample so far
per generation, on an N-sequence sample drawn from the model (and on real / true-grammar references):
  S_alpha of 4-leaf and 8-leaf blocks, alpha in {0, 0.5, 1, 2}     (support dial)
  recall of the TRUE block support, overall and for its rarest half ("tail recall")
  precision: fraction of sampled blocks valid under the true grammar
  held-out log-likelihood of REAL validation data under the model
  effective rules per level (prob > 1e-3) and the O2 dimension r* per level
"""
import json, sys, time, collections
import numpy as np

sys.path.insert(0, "/home/claude/hier")
from prefix_post import load_true

M = json.load(open("cH/rhm_meta.json"))
L, V, A = M["depth"], M["nsym"], M["nleaf"]
S = 2 ** L
TR = np.array(json.load(open("cH/train_ids.json"))).reshape(-1, S)[:20000]
VA = np.array(json.load(open("cH/val_ids.json"))).reshape(-1, S)
TRUE = load_true(M)
FIT = np.load("cH/fit.npz"); GEN0 = {l: FIT[f"P{l}"] for l in range(1, L + 1)}
N = int(sys.argv[1]) if len(sys.argv) > 1 else 20000          # training sample per generation
GENS = int(sys.argv[2]) if len(sys.argv) > 2 else 6
SWEEPS, NEVAL = 30, 20000
ARMS = sys.argv[3].split(",") if len(sys.argv) > 3 else ["replace", "accumulate"]
TAG = f"N{N}_G{GENS}" + ("" if len(sys.argv) <= 3 else "_" + "-".join(ARMS))
rng = np.random.default_rng(0)


# ------------------------------------------------------------------ grammar ops
def sample(P, n):
    Vr = P[L].shape[0]
    sym = rng.integers(0, Vr, size=(n, 1))
    for l in range(L, 0, -1):
        T = P[l].reshape(P[l].shape[0], -1)
        c = P[l].shape[1]
        cum = np.cumsum(T, 1); cum[:, -1] = 1.0
        u = rng.random(sym.shape)
        k = (u[..., None] > cum[sym]).sum(-1)
        sym = np.stack([k // c, k % c], -1).reshape(n, -1)
    return sym


def inside(X, P):
    beta = {0: np.eye(A)[X]}
    for l in range(1, L + 1):
        lo, hi = beta[l - 1][:, 0::2], beta[l - 1][:, 1::2]
        b = np.einsum("bxy,njx,njy->njb", P[l], lo, hi)
        beta[l] = b
    return beta


def loglik(X, P, chunk=4000):
    out = 0.0
    for s in range(0, len(X), chunk):
        b = inside(X[s:s + chunk], P)[L][:, 0]
        out += np.log(b.mean(1)).sum()             # uniform root prior
    return out / len(X)


def em(X, P, sweeps, chunk=4000, floor=1e-12):
    P = {l: P[l].copy() for l in P}
    for _ in range(sweeps):
        C = {l: np.zeros_like(P[l]) for l in P}
        for s in range(0, len(X), chunk):
            beta = inside(X[s:s + chunk], P)
            Vr = P[L].shape[0]
            Z = beta[L][:, 0].mean(1)                    # P(x)
            alpha = np.full((len(Z), 1, Vr), 1.0 / Vr) / Z[:, None, None]
            for l in range(L, 0, -1):
                lo, hi = beta[l - 1][:, 0::2], beta[l - 1][:, 1::2]
                C[l] += np.einsum("njb,bxy,njx,njy->bxy", alpha, P[l], lo, hi)
                if l > 1:
                    al = np.einsum("njb,bxy,njy->njx", alpha, P[l], hi)
                    ar = np.einsum("njb,bxy,njx->njy", alpha, P[l], lo)
                    a = np.empty((al.shape[0], 2 * al.shape[1], al.shape[2]))
                    a[:, 0::2], a[:, 1::2] = al, ar
                    alpha = a
        for l in P:
            T = C[l].reshape(C[l].shape[0], -1) + floor
            P[l] = (T / T.sum(1, keepdims=True)).reshape(P[l].shape)
    return P


# ------------------------------------------------------------------ true block support
def block_dist(P, level):
    """Sparse distribution over 2^level-leaf blocks (encoded base A) generated by a
    level-`level` symbol, averaged over that symbol's marginal (uniform root pushed down).
    Returns (block_ids, probs)."""
    marg = np.full(P[L].shape[0], 1.0 / P[L].shape[0])
    for l in range(L, level, -1):
        j = np.einsum("p,pxy->xy", marg, P[l]); marg = (j.sum(0) + j.sum(1)) / 2
    D = {}
    for b in range(P[1].shape[0]):
        D[b] = {x * A + y: P[1][b, x, y] for x in range(A) for y in range(A) if P[1][b, x, y] > 0}
    w = 2
    for l in range(2, level + 1):
        new = {}
        for b in range(P[l].shape[0]):
            acc = collections.defaultdict(float)
            for x, y in zip(*np.nonzero(P[l][b])):
                pr = P[l][b, x, y]
                for kx, px in D[x].items():
                    for ky, py in D[y].items():
                        acc[kx * A ** w + ky] += pr * px * py
            new[b] = dict(acc)
        D, w = new, 2 * w
    tot = collections.defaultdict(float)
    for b, m in enumerate(marg):
        for k, v in D[b].items():
            tot[k] += m * v
    ids = np.array(sorted(tot), dtype=np.int64)
    return ids, np.array([tot[k] for k in ids])


TRUE_BLK = {lv: block_dist(TRUE, lv) for lv in (2, 3)}      # 4- and 8-leaf blocks


def blocks(X, lv):
    w = 2 ** lv
    B = X.reshape(len(X), -1, w)
    idx = np.zeros(B.shape[:2], dtype=np.int64)
    for k in range(w):
        idx = idx * A + B[..., k]
    return idx.ravel()


def tsallis_profile(counts):
    p = counts / counts.sum()
    out = {}
    for a in (0.0, 0.5, 1.0, 2.0):
        if a == 1.0:
            out[a] = float(-(p * np.log(p)).sum())
        elif a == 0.0:
            out[a] = float(len(p) - 1)
        else:
            out[a] = float((1 - (p ** a).sum()) / (a - 1))
    return out


def data_metrics(X):
    m = {}
    for lv in (2, 3):
        b = blocks(X, lv)
        vals, cnt = np.unique(b, return_counts=True)
        supp, tp = TRUE_BLK[lv]
        tail = supp[tp <= np.median(tp)]
        seen = set(vals.tolist())
        m[f"S_alpha_{2**lv}"] = tsallis_profile(cnt.astype(float))
        m[f"recall_{2**lv}"] = float(np.mean([s in seen for s in supp]))
        m[f"tail_recall_{2**lv}"] = float(np.mean([s in seen for s in tail]))
        m[f"precision_{2**lv}"] = float(cnt[np.isin(vals, supp)].sum() / cnt.sum())
    return m


# ------------------------------------------------------------------ O2 r* per level
def rank(X, tol=1e-9):
    s = np.linalg.svd(X, compute_uv=False)
    return int((s > tol * max(1.0, s.max())).sum())


def psd_sqrt(G):
    w, U = np.linalg.eigh((G + G.T) / 2)
    return U @ np.diag(np.sqrt(np.clip(w, 0, None))) @ U.T


def rstar(P):
    G = {0: np.eye(A)}
    for l in range(1, L + 1):
        R = P[l].reshape(P[l].shape[0], -1)
        G[l] = R @ np.kron(G[l - 1], G[l - 1]) @ R.T
    prior = np.full(P[L].shape[0], 1.0 / P[L].shape[0])
    K = {L: np.outer(prior, prior)}
    out = {}
    for l in range(L - 1, 0, -1):
        Rp = P[l + 1]
        K[l] = np.einsum("pq,pbc,qde,ce->bd", K[l + 1], Rp, Rp, G[l])
        out[l] = rank(psd_sqrt(G[l]) @ psd_sqrt(K[l]))
    return out


def model_metrics(P):
    return dict(heldout_ll_real=float(loglik(VA, P)),
                eff_rules={l: int((P[l] > 1e-3).sum()) for l in P},
                rstar=rstar(P))


# ------------------------------------------------------------------ run
log = {"reference": {"real_data": data_metrics(TR[:NEVAL]),
                     "true_grammar_sample": data_metrics(sample(TRUE, NEVAL)),
                     "true_model": model_metrics(TRUE)}}
t0 = time.time()
for arm in ARMS:
    P, pool = GEN0, [TR[:N]]
    rows = []
    for g in range(GENS + 1):
        if g > 0:
            if arm == "fresh":                       # null: fresh REAL data, no recursion
                X = TR[(g - 1) * N:g * N]
            else:
                Xs = sample(P, N)
                pool.append(Xs)
                X = Xs if arm == "replace" else np.concatenate(pool)
            P = em(X, P, SWEEPS)
        row = dict(gen=g, **model_metrics(P), **data_metrics(sample(P, NEVAL)))
        rows.append(row)
        print(f"[{time.time()-t0:6.0f}s] {arm:>10} gen {g}: ll_real {row['heldout_ll_real']:.3f}  "
              f"S0_8 {row['S_alpha_8'][0.0]:.0f}  S.5_8 {row['S_alpha_8'][0.5]:.1f}  H_8 {row['S_alpha_8'][1.0]:.3f}  "
              f"S2_8 {row['S_alpha_8'][2.0]:.4f}  recall_8 {row['recall_8']:.3f} tail {row['tail_recall_8']:.3f}  "
              f"prec_8 {row['precision_8']:.3f}  rules {row['eff_rules']}  r* {row['rstar']}", flush=True)
    log[arm] = rows
json.dump(log, open(f"cH/collapse_{TAG}.json", "w"), indent=1, default=float)
print("reference real:", {k: v for k, v in log['reference']['real_data'].items() if '8' in k})
print("reference true-grammar sample:", {k: v for k, v in log['reference']['true_grammar_sample'].items() if '8' in k})
print("true model:", log['reference']['true_model'])
