"""The rational distribution monad D_Q as a quotient of lists (paper, Section sec:constructive), executable.

An element of D(X) is represented by a list of (x, q) with q a positive Fraction. The equivalence relation is the one
GENERATED by permutation, merging of equal points, and global scaling; for X with decidable equality its normal form is
the normalised weight function (dict x -> Fraction summing to 1), which is what `nf` computes. Everything is exact
rational arithmetic: no floats, no limits.
"""
from __future__ import annotations

from fractions import Fraction
from typing import Callable, Dict, Hashable, List, Tuple

Lst = List[Tuple[Hashable, Fraction]]


def nf(l: Lst) -> Tuple[Tuple[Hashable, Fraction], ...]:
    """normal form of a list modulo permutation, merging and scaling"""
    w = sum(q for _, q in l); acc: Dict[Hashable, Fraction] = {}
    for x, q in l:
        acc[x] = acc.get(x, Fraction(0)) + q / w
    return tuple(sorted(acc.items(), key=lambda kv: repr(kv[0])))


def equiv(a: Lst, b: Lst) -> bool:
    return nf(a) == nf(b)


def eta(x) -> Lst:
    return [(x, Fraction(1))]


def dmap(f: Callable, l: Lst) -> Lst:
    return [(f(x), q) for x, q in l]


def mu(L: List[Tuple[Lst, Fraction]]) -> Lst:
    """multiplication on a representative: a list of (list, weight); weights normalised at both levels"""
    W = sum(q for _, q in L); out = []
    for inner, q in L:
        v = sum(r for _, r in inner)
        out += [(x, q * r / (W * v)) for x, r in inner]
    return out


def strength_pair(a: Lst, b: Lst) -> Lst:
    """the product law (left strength then right); commutativity says the other order gives the same class"""
    return [((x, y), q * r) for x, q in a for y, r in b]


def strength_pair_swapped(a: Lst, b: Lst) -> Lst:
    return [((x, y), q * r) for y, r in b for x, q in a]


def condition(l: Lst, pred: Callable) -> Lst:
    """P | pred (pred decidable); defined when the conditioning event has positive mass"""
    keep = [(x, q) for x, q in l if pred(x)]
    if not keep:
        raise ValueError("conditioning on a null event")
    return keep


def vigneaux_action(l: Lst, X: Callable, F: Callable[[Lst], Fraction]) -> Fraction:
    """(X . F)(P) = sum_x P(X = x) F(P | X = x), for an observable X with decidable equality"""
    w = sum(q for _, q in l); vals = {}
    for e, q in l:
        vals[X(e)] = vals.get(X(e), Fraction(0)) + q / w
    return sum(px * F(condition(l, lambda e, x=x: X(e) == x)) for x, px in vals.items())
