"""Two facets of one model: restriction R and extension E.

Let i : Σ → S be the inclusion of a measurement cover into the information site
generated by all measurements (every set of variables has a joint there).

  R  (Vigneaux → AMB, pullback along i):  a global law P on E(X) ↦ its context
     marginals e_C = π_C(P).  Always defined.  Its image is exactly the set of
     non-contextual empirical models (T0 in functor form).

  E  (AMB → Vigneaux, extension):  e ↦ Ext(e) = {P : R(P) = e}, a convex polytope
     of global laws.  Non-empty iff CF(e) = 0.

  Identities:  P ∈ E(R(P)) always;  R(E(e)) = {e} whenever E(e) ≠ ∅.

  Graded extension:  E_max(e) = the non-contextual sub-models b ≥ 0 with R(b) ≤ e
     and maximal mass 1 − CF(e).  This is the honest form of the decomposition
     e = (1−CF)·e_NC + CF·e_ctx: it is a face of a polytope.  Whether it is a
     single point depends on the scenario.  Measured: in CHSH every contextual
     model tested has a unique optimal part (39/39); in the 3-party GHZ scenario
     none does (0/10).  canonical_nc_part picks the maximum-entropy point of the
     face, which is unique by strict concavity.

  Canonical member when E(e) ≠ ∅:  the maximum-entropy extension, found by
     iterative proportional fitting from the uniform law (Csiszár's I-projection).

The Vigneaux facet reads entropies of members of E(e); the AMB facet reads how
E fails (CF, γ).  Neither determines the other.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
from scipy.optimize import linprog

from .outcome import contextual_fraction
from .scenario import EmpiricalModel, Scenario


# ---------------------------------------------------------------- R
def restrict(scenario: Scenario, P: np.ndarray) -> EmpiricalModel:
    """R(P): context marginals of a global law on E(X)."""
    return EmpiricalModel.from_global(scenario, np.asarray(P, float))


# ---------------------------------------------------------------- E
def _constraints(model: EmpiricalModel):
    sc = model.scenario
    X = sc.measurements
    A = np.vstack([sc.restriction_matrix(X, C) for C in sc.contexts])
    b = np.concatenate([model.tables[C] for C in sc.contexts])
    return A, b


def extension_exists(model: EmpiricalModel, tol: float = 1e-9) -> bool:
    """Is Ext(e) non-empty?  Exact LP feasibility."""
    A, b = _constraints(model)
    res = linprog(np.zeros(A.shape[1]), A_eq=A, b_eq=b, bounds=(0, None), method="highs")
    return res.status == 0


def some_extension(model: EmpiricalModel) -> Optional[np.ndarray]:
    A, b = _constraints(model)
    res = linprog(np.zeros(A.shape[1]), A_eq=A, b_eq=b, bounds=(0, None), method="highs")
    return res.x if res.status == 0 else None


@dataclass
class MaxEntResult:
    P: Optional[np.ndarray]
    residual: float
    converged: bool


def max_entropy_extension(model: EmpiricalModel, iters: int = 5000, tol: float = 1e-10) -> MaxEntResult:
    """Iterative proportional fitting from the uniform law.  When Ext(e) ≠ ∅ it
    converges to the unique maximum-entropy member; otherwise it does not settle
    (the residual stays bounded away from zero) and P is returned as None."""
    sc = model.scenario
    X = sc.measurements
    R = {C: sc.restriction_matrix(X, C) for C in sc.contexts}
    P = np.full(R[sc.contexts[0]].shape[1], 1.0 / R[sc.contexts[0]].shape[1])
    for _ in range(iters):
        for C in sc.contexts:
            m = R[C] @ P
            ratio = np.divide(model.tables[C], m, out=np.zeros_like(m), where=m > 0)
            P = P * (R[C].T @ ratio)
        res = max(float(np.abs(R[C] @ P - model.tables[C]).max()) for C in sc.contexts)
        if res < tol:
            return MaxEntResult(P / P.sum(), res, True)
    return MaxEntResult(None, res, False)


# ---------------------------------------------------------------- graded E
@dataclass
class GradedExtension:
    cf: float
    b: np.ndarray                 # one optimal non-contextual sub-model (mass 1 − CF)
    unique: Optional[bool]        # is the optimal face a single point?
    spread: float                 # max over coordinates of (max − min) on the optimal face


def graded_extension(model: EmpiricalModel, check_unique: bool = True, tol: float = 1e-7) -> GradedExtension:
    cfr = contextual_fraction(model)
    A, b = _constraints(model)
    n = A.shape[1]
    ncf = 1.0 - cfr.value
    unique, spread = None, 0.0
    if check_unique:
        # optimal face: R(b) ≤ e, Σb = NCF, b ≥ 0.  Range of each coordinate over it.
        for k in range(n):
            lo = linprog(np.eye(n)[k], A_ub=A, b_ub=b, A_eq=np.ones((1, n)), b_eq=[ncf],
                         bounds=(0, None), method="highs")
            hi = linprog(-np.eye(n)[k], A_ub=A, b_ub=b, A_eq=np.ones((1, n)), b_eq=[ncf],
                         bounds=(0, None), method="highs")
            if lo.status == 0 and hi.status == 0:
                spread = max(spread, -hi.fun - lo.fun)
        unique = spread < tol
    return GradedExtension(cfr.value, cfr.noncontextual_part, unique, spread)


def canonical_nc_part(model: EmpiricalModel) -> np.ndarray:
    """Maximum-entropy point of the optimal face (unique by strict concavity)."""
    from scipy.optimize import minimize
    A, b = _constraints(model)
    g = graded_extension(model, check_unique=False)
    ncf = 1.0 - g.cf
    n = A.shape[1]
    if ncf <= 1e-12:
        return np.zeros(n)
    x0 = np.clip(g.b, 1e-9, None) * ncf / max(np.clip(g.b, 1e-9, None).sum(), 1e-300)
    f = lambda x: float(np.sum(np.clip(x, 1e-15, None) * np.log(np.clip(x, 1e-15, None))))
    jac = lambda x: np.log(np.clip(x, 1e-15, None)) + 1.0
    cons = [dict(type="eq", fun=lambda x: x.sum() - ncf, jac=lambda x: np.ones(n)),
            dict(type="ineq", fun=lambda x: b - A @ x, jac=lambda x: -A)]
    res = minimize(f, x0, jac=jac, bounds=[(0, None)] * n, constraints=cons, method="SLSQP",
                   options=dict(maxiter=2000, ftol=1e-14))
    return np.clip(res.x, 0, None)


# ---------------------------------------------------------------- one stream vs two streams
def latent_class_em(windows: np.ndarray, n_labels: int, n_classes: int, iters: int = 200,
                    rng: Optional[np.random.Generator] = None):
    """EM for a latent class model on fixed-length windows of a label stream:
    P(x_1..x_w) = Σ_z π_z Π_i θ_z,i(x_i).  Returns (π, θ) and the fitted joint on
    E(X) as a flat array (lexicographic order)."""
    import itertools
    rng = rng or np.random.default_rng(0)
    n, w = windows.shape
    pi = np.full(n_classes, 1.0 / n_classes)
    th = rng.dirichlet(np.ones(n_labels), size=(n_classes, w))
    for _ in range(iters):
        lp = np.log(pi)[None, :] + sum(np.log(th[:, i, windows[:, i]]).T for i in range(w))
        lp -= lp.max(1, keepdims=True)
        r = np.exp(lp)
        r /= r.sum(1, keepdims=True)
        pi = r.mean(0)
        for i in range(w):
            for x in range(n_labels):
                th[:, i, x] = r[windows[:, i] == x].sum(0) + 1e-9
            th[:, i] /= th[:, i].sum(1, keepdims=True)
    joint = np.array([sum(pi[z] * np.prod([th[z, i, xs[i]] for i in range(w)]) for z in range(n_classes))
                      for xs in itertools.product(range(n_labels), repeat=w)])
    return pi, th, joint / joint.sum()


def window_counts(scenario: Scenario, windows: np.ndarray) -> EmpiricalModel:
    """Empirical model reading every context off the SAME windows (single source)."""
    X = scenario.measurements
    idx = {m: k for k, m in enumerate(X)}
    counts = {}
    for C in scenario.contexts:
        secs = scenario.sections(C)
        pos = {s: k for k, s in enumerate(secs)}
        c = np.zeros(len(secs))
        for row in windows:
            c[pos[tuple(scenario.outcomes[m][row[idx[m]]] for m in C)]] += 1
        counts[C] = c
    return EmpiricalModel.from_counts(scenario, counts)
