"""Cup and Massey products in the pointwise information complex.

Setting. Variables V_1..V_m (finite values); observables = nonempty subsets of variables, product = union.
Pointwise coefficients: an n-cochain assigns to observables (X_1, ..., X_n) and a law P a function of the
outcome w, f[X_1|...|X_n](P)(w), LOCAL: it depends only on the law of X_1...X_n and on its value at w.
Action (pointwise conditioning):  (X.g)(P)(w) = g(P | X = X(w))(w).
This action is MULTIPLICATIVE, X.(fg) = (X.f)(X.g), so the cochains form a differential graded algebra.
(The averaged Shannon action is not multiplicative, which is why Vigneaux's cup product needs F (x) F.)

  (delta f)[X_1|..|X_{n+1}] = X_1.f[X_2|..|X_{n+1}] + sum_{i=1}^n (-1)^i f[..|X_i X_{i+1}|..] + (-1)^{n+1} f[X_1|..|X_n]
  (f cup g)[X_1|..|X_{n+m}] = f[X_1|..|X_n] * (X_1...X_n).g[X_{n+1}|..|X_{n+m}]

Degree-1 class: pointwise surprisal s[X](P)(w) = -log P(X = X(w)).
Result (checked numerically below and in tests): with u_1 = s and u_n = s^n / n! (as local 1-cochains),
      delta u_n = - sum_{i+j=n, i,j>=1} u_i cup u_j ,
so the defining systems of all Massey powers <s, s, ..., s> exist and contain 0: the A-infinity structure
generated by s is formal. The generating function is sum_n u_n = e^{s} - 1 = 1/P - 1.
"""
from __future__ import annotations
import itertools
import numpy as np


class Structure:
    def __init__(self, sizes=(2, 2, 2)):
        self.sizes = tuple(sizes); self.m = len(sizes)
        self.outcomes = list(itertools.product(*[range(k) for k in sizes]))
        self.obs = [frozenset(c) for r in range(1, self.m + 1) for c in itertools.combinations(range(self.m), r)]

    def prob(self, P, X, w, cond=None):
        """P(X = X(w) | cond) where cond is a list of (observable, value-outcome) constraints"""
        mask = np.ones(len(self.outcomes), bool)
        for Y, v in (cond or []):
            mask &= np.array([all(o[i] == v[i] for i in Y) for o in self.outcomes])
        sel = mask & np.array([all(o[i] == w[i] for i in X) for o in self.outcomes])
        return P[sel].sum() / P[mask].sum()


class Cochain:
    """f(obs_tuple, P, w, cond) -> float; cond encodes conditioning applied by the action (a list)."""
    def __init__(self, deg, fn):
        self.deg, self.fn = deg, fn

    def __call__(self, Xs, P, w, cond=()):
        return self.fn(Xs, P, w, list(cond))


def act(X, g_val, w):
    """helper: the action X. on a cochain value is implemented by appending the constraint (X, w)"""
    return (X, w)


def delta(S: Structure, f: Cochain) -> Cochain:
    n = f.deg

    def fn(Xs, P, w, cond):
        X1 = Xs[0]
        out = f(Xs[1:], P, w, cond + [(X1, w)])
        for i in range(n):
            merged = Xs[:i] + (Xs[i] | Xs[i + 1],) + Xs[i + 2:]
            out += (-1) ** (i + 1) * f(merged, P, w, cond)
        out += (-1) ** (n + 1) * f(Xs[:-1], P, w, cond)
        return out
    return Cochain(n + 1, fn)


def cup(f: Cochain, g: Cochain) -> Cochain:
    n = f.deg

    def fn(Xs, P, w, cond):
        head = frozenset().union(*Xs[:n])
        return f(Xs[:n], P, w, cond) * g(Xs[n:], P, w, cond + [(head, w)])
    return Cochain(n + g.deg, fn)


def add(*cs, coef=None):
    coef = coef or [1.0] * len(cs)

    def fn(Xs, P, w, cond):
        return sum(c * x(Xs, P, w, cond) for c, x in zip(coef, cs))
    return Cochain(cs[0].deg, fn)


def surprisal_power(S: Structure, n: int) -> Cochain:
    """u_n[X](P)(w) = (-log P(X=X(w)))^n / n!   (u_1 = s)"""
    from math import factorial

    def fn(Xs, P, w, cond):
        return (-np.log(S.prob(P, Xs[0], w, cond))) ** n / factorial(n)
    return Cochain(1, fn)


def max_abs(S: Structure, c: Cochain, trials=20, seed=0):
    rng = np.random.default_rng(seed); worst = 0.0
    for _ in range(trials):
        P = rng.dirichlet(np.ones(len(S.outcomes)))
        for Xs in itertools.product(S.obs, repeat=c.deg):
            w = S.outcomes[rng.integers(len(S.outcomes))]
            worst = max(worst, abs(c(Xs, P, w)))
    return worst


def massey_report(sizes=(2, 2, 2), N=4, trials=10):
    S = Structure(sizes)
    u = {k: surprisal_power(S, k) for k in range(1, N + 1)}
    rep = {"delta s": max_abs(S, delta(S, u[1]), trials)}
    for n in range(2, N + 1):
        rhs = add(*[cup(u[i], u[n - i]) for i in range(1, n)])
        rep[f"delta u_{n} + sum u_i cup u_j (n={n})"] = max_abs(S, add(delta(S, u[n]), rhs), trials)
    # Leibniz check on a random pair
    f, g = u[1], u[2]
    lhs = delta(S, cup(f, g)); r = add(cup(delta(S, f), g), cup(f, delta(S, g)), coef=[1.0, -1.0])
    rep["Leibniz delta(fg) - (df g - f dg)"] = max_abs(S, add(lhs, r, coef=[1.0, -1.0]), trials)
    return rep
