"""
IS THE PLAQUETTE CURVATURE PREDICTED BY GRADIENTS OF THE HAZARD FIELD r?
Plaquette: coarse tiles (i, i+1) at layer A, their children at layer B (ratio 2).
  F_square = || M_v(i+1) M_h^A(i)  -  M_h^B(2i) M_v(i) ||  / scale
  grad_r   = total variation of mean r around the plaquette
Correlate across plaquettes. If curvature tracks grad r, the connection lives
over optimiser state rather than over the parameter lattice.
"""
import time, gc, numpy as np, torch
t0=time.time()
g_={}; src=open("/mnt/user-data/uploads/compiler_geometri_patched_86.py").read()
exec(src[:src.find("# ── PHASE 1")], g_)
model=g_["model"]; get_batch=g_["get_batch"]; LR=g_["LR"]
named=list(model.named_parameters())
def flat(): return torch.cat([p.data.flatten() for _,p in named]).clone()
def state(o,k):
    out=[]
    for _,p in named:
        s=o.state.get(p,{}); out.append(s[k].flatten() if k in s else torch.zeros(p.numel()))
    return torch.cat(out)
P=flat().numel(); NA=128; NB=256          # coarse / fine, ratio 2
segA=(torch.arange(P)*NA//P).long(); segB=(torch.arange(P)*NB//P).long()
cA=torch.bincount(segA,minlength=NA).float(); cB=torch.bincount(segB,minlength=NB).float()
model.load_state_dict(torch.load("init.pt")); torch.manual_seed(17)
o=torch.optim.AdamW(model.parameters(), lr=LR*5, betas=(0.9,0.95), weight_decay=0.1)
XA=[];XB=[];RA=[];RB=[]
prev=flat()
for s in range(1,121):
    model.train(); x,y=get_batch(); _,l=model(x,y)
    o.zero_grad(); l.backward(); torch.nn.utils.clip_grad_norm_(model.parameters(),1.0)
    b4=flat(); o.step(); af=flat(); d=af-b4
    m=state(o,"exp_avg").abs(); v=state(o,"exp_avg_sq").sqrt(); r=m/(v+1e-12)
    ad=d.abs()
    dA=torch.zeros(NA).index_add_(0,segA,ad)/cA; rA=torch.zeros(NA).index_add_(0,segA,r)/cA
    dB=torch.zeros(NB).index_add_(0,segB,ad)/cB; rB=torch.zeros(NB).index_add_(0,segB,r)/cB
    XA.append(np.stack([np.log(dA.numpy()+1e-30), np.log(rA.numpy()+1e-30)],1))
    XB.append(np.stack([np.log(dB.numpy()+1e-30), np.log(rB.numpy()+1e-30)],1))
    RA.append(rA.numpy()); RB.append(rB.numpy())
    prev=af; del b4,af,d,m,v,r
    if s%40==0: gc.collect(); print(f"    step {s} ({time.time()-t0:.0f}s)", flush=True)
XA=np.stack(XA); XB=np.stack(XB); RA=np.stack(RA).mean(0); RB=np.stack(RB).mean(0)
def fit(A,B):
    M,_,_,_=np.linalg.lstsq(A,B,rcond=None); return M.T
print(f"\n  fitted from {XA.shape[0]} steps  ({time.time()-t0:.0f}s)")
F=[]; G=[]; NRM=[]
for i in range(NA-1):
    Mh_A = fit(XA[:,i,:],   XA[:,i+1,:])       # coarse horizontal  i -> i+1
    Mv_i = fit(XA[:,i,:],   XB[:,2*i,:])       # vertical  i -> child 2i
    Mv_j = fit(XA[:,i+1,:], XB[:,2*i+2,:])     # vertical  i+1 -> child 2i+2
    Mh_B = fit(XB[:,2*i,:], XB[:,2*i+2,:])     # fine horizontal
    p1 = Mv_j@Mh_A; p2 = Mh_B@Mv_i
    sc=max(np.linalg.norm(p1),1e-30)
    F.append(np.linalg.norm(p1-p2)/sc); NRM.append(sc)
    G.append(abs(RA[i+1]-RA[i])/max(RA[i],1e-30)
             + abs(RB[2*i]-RA[i])/max(RA[i],1e-30))
F=np.array(F); G=np.array(G)
print("="*80); print("  PLAQUETTE CURVATURE vs HAZARD-FIELD VARIATION"); print("="*80)
print(f"  plaquettes: {len(F)}")
print(f"  curvature  |F_sq|: mean {F.mean():.4f}  median {np.median(F):.4f}"
      f"  range [{F.min():.4f}, {F.max():.4f}]")
print(f"  grad r     : mean {G.mean():.4f}  median {np.median(G):.4f}")
from scipy.stats import spearmanr
print(f"\n  corr(F_sq, grad r)   Pearson {np.corrcoef(F,G)[0,1]:+.3f}"
      f"   Spearman {spearmanr(F,G).statistic:+.3f}")
print(f"  corr(log F, log grad r)  Pearson "
      f"{np.corrcoef(np.log(F+1e-9),np.log(G+1e-9))[0,1]:+.3f}")
lo=F[G<np.median(G)]; hi=F[G>=np.median(G)]
print(f"\n  mean |F_sq| in low-grad-r half  = {lo.mean():.4f}")
print(f"  mean |F_sq| in high-grad-r half = {hi.mean():.4f}   ratio {hi.mean()/max(lo.mean(),1e-30):.2f}x")
print(f"\n  fraction of plaquettes with |F_sq| < 0.05 (near-flat): {100*np.mean(F<0.05):.1f}%")
print("\n  strong positive correlation => curvature is generated by hazard gradients")
print(f"\n  time {time.time()-t0:.0f}s")
