"""Hand labels for the 100 BASIL events (auditable; change freely).
theme: ELECT (campaigns, candidacies, party leadership), INVEST (scandal, investigation, legal, apology),
       POLICY (legislation, budget, immigration, guns, trade, security), SOCIAL (religion, sexuality, race, culture)
camp:  party of the focal actor(s) the story is about: R, D, or N (neither/mixed)."""
L = {
"Glenn Beck speaks at CPAC": ("ELECT", "R"),
"Michael Steele Criticized for Afghanistan Comments": ("INVEST", "R"),
"Michael Steele about to announce whether he'll run again for RNC chairman": ("ELECT", "R"),
"N.A.A.C.P. Challenges Tea Party on Racism": ("SOCIAL", "R"),
"Rep Etheridge apologizes for grabbing a young man": ("INVEST", "D"),
"Republican congressional candidates dispute plans to build mosque near ground zero": ("SOCIAL", "R"),
"Republicans threaten to filibuster legislation until tax cuts are passed": ("POLICY", "R"),
"Richard Blumenthal lies about serving in Vietnam war": ("INVEST", "D"),
"White House Asked Bill Clinton to Urge Sestak to Drop Out of Senate Race": ("ELECT", "D"),
"White House pressures congress to pass tax bill": ("POLICY", "D"),
"AARP drops its opposition to Social Security cuts": ("POLICY", "N"),
"Donald Trump drops plans to moderate presidential debate": ("ELECT", "R"),
"House Reading of Constitution Is Not Without Issues": ("POLICY", "R"),
"Joe Arpaio endorsed Texas Governor Rick Perry for the Republican presidential nomination": ("ELECT", "R"),
"Newsweek publishes unflattering cover of Michele Bachmann": ("ELECT", "R"),
"Obama taunts GOP for ignoring jobs bill": ("POLICY", "D"),
"Rick Perry claims to defend feith in America after calling President Obama is waging a \"War on Religion\"": ("SOCIAL", "R"),
"Trump holds birther meeting": ("ELECT", "R"),
"Walmart sex discrimination case goes to supreme court": ("SOCIAL", "N"),
"Weiner Denies Sending Photo": ("INVEST", "D"),
"Benjamin Netanyahu Used In Conservative Attack Ad Against Obama": ("ELECT", "R"),
"Biden and Ryan debate": ("ELECT", "N"),
"GOP reps show support for Chick-Fil-A": ("SOCIAL", "R"),
"Georgetown Catholics challenge Paul Ryan": ("SOCIAL", "R"),
"John Boehner discusses chance GOP will lose House": ("ELECT", "R"),
"Obama and Boehner discuss deficits": ("POLICY", "N"),
"Obama and Romney campaigns argue on Medicare": ("ELECT", "N"),
"Rick Santorum defends his comments on Obama": ("ELECT", "R"),
"Romney reaffirms opposition to same sex marriage": ("SOCIAL", "R"),
"Romney urges Akin to drop out of Senate race": ("ELECT", "R"),
"I.R.S. Official Invokes 5th Amendment at Hearing": ("INVEST", "D"),
"Jackson pleads guilty over illegal campaign spending spree": ("INVEST", "D"),
"Legally married same-sex couples will now be allowed to file federal joint tax returns": ("SOCIAL", "D"),
"Mary Cheney criticizes sister Liz on same-sex marriage": ("SOCIAL", "R"),
"NRA and Hutchinson recommends schools to have armed staff": ("POLICY", "R"),
"Obama urges new restrictions on assault weapons": ("POLICY", "D"),
"Republicans challenge Clinton claims on budget cuts, Benghazi cable": ("INVEST", "D"),
"White House Plays Down Data Program": ("POLICY", "D"),
"White House releases e-mails relating to the Benghazi talking points": ("INVEST", "D"),
"William Cowan named interim senator in Massachusetts": ("ELECT", "D"),
"Bruce Braley apologizes for farmer comments": ("INVEST", "D"),
"Christ Christie campaign documents subpoenaed": ("INVEST", "R"),
"Elizabeth Lauten apologizes for criticizing Obama daughters": ("INVEST", "R"),
"Eric Cantor defeated by David Brat": ("ELECT", "R"),
"Eric Holder speaks on Ferguson": ("SOCIAL", "D"),
"Federal charges filed against Grimm": ("INVEST", "R"),
"House Republicans offer broad immigration plan": ("POLICY", "R"),
"Jan Brewer urged to veto gay discrimination bill": ("SOCIAL", "R"),
"Nebraska and Oklahoma fight Colorado's recreational marijuana policy": ("POLICY", "N"),
"Raul Labrador challenges Kevin McCarthy for House majority leadership": ("ELECT", "R"),
"Benghazi committee wants to interview Clinton about emails": ("INVEST", "D"),
"Chris Christie announces bid for presidency": ("ELECT", "R"),
"Hillary Clinton asks state department to vet emails for release": ("INVEST", "D"),
"Hillary Clinton releases tax returns": ("ELECT", "D"),
"Hillary Clinton suggests Obama should listen to his allies  on trade": ("POLICY", "D"),
"Marco Rubio announces his foreign policy": ("ELECT", "R"),
"Mike Huckabee announced his run for the presidency": ("ELECT", "R"),
"Mike Pence seeks legislation to clarify the Religious Freedom Restoration Act": ("SOCIAL", "R"),
"Netanyahu plans to deliver a speech to Congress": ("POLICY", "R"),
"state legislature passed a new version of the Religious Freedom Reformation Act": ("SOCIAL", "R"),
"Bloomberg criticizes Trump at DNC": ("ELECT", "D"),
"Fox and Calder say Mexico isn't paying for border wall": ("POLICY", "R"),
"Nancy Pelosi wins House minority leadership again": ("ELECT", "D"),
"Obama to meet with Bernie Sanders": ("ELECT", "D"),
"Paul LePage remains in office": ("INVEST", "R"),
"Ruth Bader Ginsburg criticizes Trump": ("ELECT", "N"),
"Senate set to override Obama's veto on 9/11 bill": ("POLICY", "N"),
"Trump and Cruz argue over personal attacks": ("ELECT", "R"),
"Trump criticizes Obama and Clinton over Orlando shooting": ("POLICY", "R"),
"Trump gets into Twitter feud with Vicente Fox": ("ELECT", "R"),
"Donald Trump Jr. Messaged With WikiLeaks During Presidential Campaign": ("INVEST", "R"),
"Donald Trump considers Joe Lieberman for FBI Director": ("POLICY", "R"),
"Donald Trump is inaugurated": ("ELECT", "R"),
"Flynn pleaded guilty": ("INVEST", "R"),
"House Intelligence committee prepares to subpoena Michael Flynn": ("INVEST", "R"),
"Kathy Griffin apologizes for photo shoot with a fake bloody Donald Trump head": ("INVEST", "D"),
"Rare comity at Capitol after shooting doesn't last": ("SOCIAL", "N"),
"Supreme Court nomination of Judge Neil M. Gorsuch": ("POLICY", "R"),
"Trump reverses decision to allow import of elephant trophies": ("POLICY", "R"),
"White House responds to sexual misconduct allegations against Roy Moore": ("INVEST", "R"),
"Blake Farenthold resigns from Congress": ("INVEST", "R"),
"Cesar Sayoc arrested for sending pipe bombs to Trump critics": ("INVEST", "N"),
"Congressman Hunter and wife indicted on corruption charges": ("INVEST", "R"),
"Democrats Say Trump Should Cancel Putin Meeting After Indictments": ("INVEST", "R"),
"James Mattis quits as defense secretary": ("POLICY", "R"),
"Schumer bashed by the left over shutdown-ending deal": ("POLICY", "D"),
"Trump Accuses Former Clinton Aide of Failing to Follow Security Protocols": ("INVEST", "D"),
"Trump Accuses Social Media Firms of Discrimination Against Conservatives": ("SOCIAL", "R"),
"Trump critic Peter Strzok fired from FBI": ("INVEST", "R"),
"Trump intends to end birthright citizenship": ("POLICY", "R"),
"Democrats demand release of full Mueller report": ("INVEST", "R"),
"Democrats pass campaign finance and voting rights reform bill": ("POLICY", "D"),
"Democrats react to Rashida Tlaib's comments": ("SOCIAL", "D"),
"Donald Trump announces end to government shutdown": ("POLICY", "R"),
"House Intelligence Committee demand Adam Schiff's resignation": ("INVEST", "D"),
"Lawmakers react to Trump's immigration proposal": ("POLICY", "R"),
"Mueller’s office disputes BuzzFeed report": ("INVEST", "R"),
"Roger Stone has been indicted by Mueller": ("INVEST", "R"),
"Trump continues government shutdown for border wall": ("POLICY", "R"),
"Trump declares national emergency over border wall": ("POLICY", "R"),
}


def triplet_labels(basil=None):
    """triplet-uuid -> (theme, camp, canonical event string), using whichever article's main-event is labelled"""
    import glob, json, os
    basil = basil or os.environ.get("BASIL_DIR", "data/BASIL")
    out = {}
    for f in glob.glob(f"{basil}/articles/*/*.json"):
        d = json.load(open(f))
        if d["main-event"] in L:
            out[d["triplet-uuid"]] = L[d["main-event"]] + (d["main-event"],)
    return out
